# Generated by Django 3.2.17 on 2024-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task_name',
            new_name='task_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=0),
        ),
    ]
